# NumPy

In [1]:
import numpy as np

## NumPy Array

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(type(lista))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Indexado 
arr[0]

0

In [7]:
arr[1] + arr[5]

6

In [8]:
matriz[0]

array([1, 2, 3])

In [9]:
matriz[0,2]

3

In [10]:
matriz[0][2]

3

In [11]:
#Slicing 
arr[0:3]

array([0, 1, 2])

In [12]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [13]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[::3]

array([0, 3, 6, 9])

In [16]:
arr[::2]

array([0, 2, 4, 6, 8])

In [17]:
arr[-1]

9

In [18]:
arr[-3:]

array([7, 8, 9])

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos

In [21]:
arreglo = np.array([0,1,2,3,4,5])
arreglo

array([0, 1, 2, 3, 4, 5])

In [22]:
arreglo.dtype

dtype('int32')

In [23]:
arreglo = np.array([0,1,2,3,4,5], dtype='float64')
arreglo

array([0., 1., 2., 3., 4., 5.])

In [24]:
arreglo.dtype

dtype('float64')

In [25]:
arreglo1 = np.array([0,1,2,3,4,5])
arreglo1

array([0, 1, 2, 3, 4, 5])

In [26]:
arreglo1 = arreglo1.astype(np.float64)
arreglo1

array([0., 1., 2., 3., 4., 5.])

In [27]:
arreglo1.dtype

dtype('float64')

In [28]:
arreglo2 = np.array([0,1,2,3])
arreglo2 = arreglo2.astype(np.bool_)
arreglo2

array([False,  True,  True,  True])

In [29]:
arreglo3 = np.array([0,1,2,3])
arreglo3 = arreglo3.astype(np.string_)
arreglo3

array([b'0', b'1', b'2', b'3'], dtype='|S11')

In [30]:
arreglo4 = np.array(['0','1','2','3'])
arreglo4 = arreglo4.astype(np.int8)
arreglo4

array([0, 1, 2, 3], dtype=int8)

## Dimensiones

In [31]:
escalar = np.array(45)
print(escalar)
print('Dimensión: ',escalar.ndim)

45
Dimensión:  0


In [32]:
vector = np.array([1,2,3])
print(vector)
print('Dimensión: ',vector.ndim)

[1 2 3]
Dimensión:  1


In [33]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print('Dimensión: ',matriz.ndim)

[[1 2 3]
 [4 5 6]]
Dimensión:  2


In [34]:
matriz = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(matriz)
print('Dimensión: ',matriz.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensión:  2


In [35]:
tensor = np.array([[[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]]])
print(tensor)
print('Dimensión: ',tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensión:  3


In [36]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
print('Dimensión: ',vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensión:  10


In [37]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
print('Dimensión: ', expand.ndim)

[[1 2 3]]
Dimensión:  2


In [38]:
print(vector,'Dimensión: ',vector.ndim)
vector1 = np.squeeze(vector)
print(vector1, 'Dimensión: ',vector1.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] Dimensión:  10
[1 2 3] Dimensión:  1


## Creando arrays

In [39]:
range(0,10)

range(0, 10)

In [40]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
# (inicio, fin, cantidad_de_datos)
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [47]:
# Matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# Número aleatorio
np.random.rand()

0.13609011125919035

In [49]:
np.random.rand(4)

array([0.56065915, 0.90608111, 0.53291153, 0.21756176])

In [50]:
np.random.rand(3,3,3)

array([[[0.53243928, 0.23610061, 0.3889346 ],
        [0.5772818 , 0.78941243, 0.30620139],
        [0.83085407, 0.72496001, 0.88344011]],

       [[0.90151294, 0.87090289, 0.25921778],
        [0.91749516, 0.47743292, 0.63599718],
        [0.04583379, 0.21765056, 0.85602703]],

       [[0.91232667, 0.12067584, 0.09018239],
        [0.73746595, 0.13080115, 0.51581686],
        [0.68029845, 0.47421147, 0.33572167]]])

In [51]:
np.random.randint(1,15)

9

In [52]:
np.random.randint(1,100,(10,10))

array([[33,  9, 63,  3, 61,  6, 84, 27, 43, 15],
       [17, 39, 78, 43, 10,  1, 99, 68, 18, 62],
       [99, 15, 72, 27, 89, 29, 84, 24, 98, 23],
       [46, 61, 93, 24, 57, 28, 67, 59, 81, 42],
       [19, 23, 33, 19, 69, 20, 17, 75, 43,  1],
       [74, 85, 17, 78, 64, 71, 91, 36, 37, 25],
       [30, 72, 51, 66, 35, 76, 91, 45,  4, 11],
       [73,  9, 46, 20,  4, 61, 18, 30, 40, 27],
       [84, 81, 87,  2, 80, 89, 97, 16, 52, 44],
       [79, 94, 15, 16, 81, 97, 56, 17, 19, 77]])

In [53]:
np.random.randint(1,100,(10,10,3))

array([[[39, 95, 53],
        [87, 34, 24],
        [53, 48, 93],
        [35, 89, 65],
        [96,  5, 50],
        [69, 38, 18],
        [98, 18, 98],
        [74, 56, 64],
        [ 7, 67, 22],
        [61, 22, 55]],

       [[ 2, 22, 72],
        [76, 70, 12],
        [66, 68, 78],
        [43, 50,  1],
        [35, 14, 66],
        [ 8, 43, 31],
        [60, 77, 22],
        [78, 13, 92],
        [43, 45, 78],
        [67,  6, 81]],

       [[57, 51, 14],
        [31, 64, 73],
        [20, 90, 31],
        [10, 43, 32],
        [46,  6, 45],
        [44, 70, 41],
        [39,  8, 78],
        [ 4, 16, 25],
        [60, 56, 53],
        [67, 14, 75]],

       [[57,  2, 90],
        [19, 37, 69],
        [63, 31, 13],
        [56, 74, 93],
        [24, 18, 86],
        [57, 57, 67],
        [96, 95,  8],
        [19, 72, 11],
        [16, 58, 17],
        [63, 70, 36]],

       [[41,  6, 57],
        [40, 90, 38],
        [52, 20, 52],
        [41, 80, 71],
        [94, 91, 90],
  

## Shape y Reshape

In [55]:
arreglo = np.random.randint(1,10,(3,2))
arreglo

array([[6, 7],
       [9, 1],
       [5, 4]])

In [56]:
arreglo.shape

(3, 2)

In [57]:
arreglo.reshape(1,6)

array([[6, 7, 9, 1, 5, 4]])

In [65]:
# Si no cumple la cantidad elementos del arreglo con la nueva dimensionalidad, genera un error
arreglo.reshape(1,7)

ValueError: cannot reshape array of size 6 into shape (1,7)

In [58]:
arreglo.reshape(2,3)

array([[6, 7, 9],
       [1, 5, 4]])

In [59]:
np.reshape(arreglo,(1,6))

array([[6, 7, 9, 1, 5, 4]])

In [62]:
# Reorganiza por filas
np.reshape(arreglo,(2,3), 'C')

array([[6, 7, 9],
       [1, 5, 4]])

In [63]:
# Reorganiza por columnas
np.reshape(arreglo,(2,3), 'F')

array([[6, 5, 1],
       [9, 7, 4]])

In [64]:
# Reorganiza según este optimizado nuestra maquina
np.reshape(arreglo,(2,3), 'A')

array([[6, 7, 9],
       [1, 5, 4]])

## Funciones principales de NumPy

In [67]:
arreglo = np.random.randint(1,20,10)
arreglo

array([ 3,  5,  5,  6,  3, 13,  5, 15, 18,  7])

In [69]:
matriz = arreglo.reshape(2,5)
matriz

array([[ 3,  5,  5,  6,  3],
       [13,  5, 15, 18,  7]])

In [70]:
arreglo.max()

18

In [78]:
arreglo.min()

3

In [71]:
matriz.max()

18

In [79]:
matriz.min()

3

In [72]:
matriz.max(1)

array([ 6, 18])

In [73]:
matriz.max(0)

array([13,  5, 15, 18,  7])

In [80]:
matriz.min(0)

array([3, 5, 5, 6, 3])

In [74]:
# Indice donde se encuentra el valor màs grande
arreglo.argmax()

8

In [81]:
arreglo.argmin()

0

In [75]:
matriz.argmax()

8

In [82]:
matriz.argmin()

0

In [76]:
matriz.argmax(0)

array([1, 0, 1, 1, 1], dtype=int64)

In [83]:
matriz.argmin(0)

array([0, 0, 0, 0, 0], dtype=int64)

In [77]:
matriz.argmax(1)

array([3, 3], dtype=int64)

In [84]:
matriz.argmin(1)

array([0, 1], dtype=int64)

In [85]:
arreglo.ptp()

15

In [86]:
matriz.ptp()

15

In [87]:
matriz.ptp(0)

array([10,  0, 10, 12,  4])

In [88]:
matriz.ptp(1)

array([ 3, 13])

In [89]:
np.percentile(arreglo,50)

5.5

In [90]:
np.percentile(arreglo,0)

3.0

In [91]:
np.percentile(arreglo,100)

18.0

In [93]:
arreglo.sort()
arreglo

array([ 3,  3,  5,  5,  5,  6,  7, 13, 15, 18])

In [94]:
np.median(arreglo)

5.5

In [95]:
np.median(matriz,0)

array([ 4.5,  5. ,  9. , 10. , 11.5])

In [96]:
np.median(matriz,1)

array([ 5., 13.])

In [97]:
np.std(arreglo)

5.059644256269407

In [98]:
np.var(arreglo)

25.6

In [99]:
np.mean(arreglo)

8.0

In [100]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [101]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [102]:
a

array([[1, 2],
       [3, 4]])

In [103]:
a.T

array([[1, 3],
       [2, 4]])

In [104]:
b

array([[5, 6],
       [7, 8]])

In [105]:
b.T

array([[5, 7],
       [6, 8]])

## Copy

In [106]:
arreglo = np.arange(0,11)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr = arreglo[0:6]
arr

array([0, 1, 2, 3, 4, 5])

In [109]:
arr[:] = 0
arr

array([0, 0, 0, 0, 0, 0])

In [110]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [111]:
arreglo_copy = arreglo.copy()
arreglo_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [112]:
arreglo_copy[:] = 100
arreglo_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [113]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [114]:
arreglo == arreglo_copy

array([False, False, False, False, False, False, False, False, False,
       False, False])

## Condiciones

In [115]:
arreglo = np.linspace(1,10,10, dtype='int8')
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [116]:
arreglo > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [117]:
indices_condicion = arreglo > 5
indices_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [118]:
arreglo[indices_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [119]:
arreglo[(arreglo > 5) & (arreglo < 9)]

array([6, 7, 8], dtype=int8)

In [120]:
arreglo[arreglo>5] = 99
arreglo

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [121]:
arreglo[arreglo==99]

array([99, 99, 99, 99, 99], dtype=int8)

## Operaciones

In [122]:
lista = [1,2]
lista

[1, 2]

In [123]:
lista * 2

[1, 2, 1, 2]

In [126]:
lista * 3

[1, 2, 1, 2, 1, 2]

In [124]:
arreglo = np.arange(0,10)
arreglo1 = arreglo.copy()
arreglo1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arreglo * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [127]:
arreglo + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [128]:
1 / arreglo

C:\Users\usuario\AppData\Local\Temp\ipykernel_12968\3939086782.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arreglo


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [129]:
arreglo ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [130]:
arreglo + arreglo1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [131]:
arreglo * arreglo1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [132]:
arreglo / arreglo1

C:\Users\usuario\AppData\Local\Temp\ipykernel_12968\3264456223.py:1: RuntimeWarning: invalid value encountered in true_divide
  arreglo / arreglo1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [133]:
matriz = arreglo.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
matriz1 = matriz.copy()
matriz1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
matriz + matriz1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [138]:
matriz * matriz1

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [139]:
matriz - matriz1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [141]:
# Producto punto
np.matmul(matriz, matriz1.T)

array([[ 30,  80],
       [ 80, 255]])

In [142]:
matriz @ matriz1.T

array([[ 30,  80],
       [ 80, 255]])