# NumPy

In [1]:
import numpy as np

## NumPy Array

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(type(lista))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Indexado 
arr[0]

0

In [7]:
arr[1] + arr[5]

6

In [8]:
matriz[0]

array([1, 2, 3])

In [9]:
matriz[0,2]

3

In [10]:
matriz[0][2]

3

In [11]:
#Slicing 
arr[0:3]

array([0, 1, 2])

In [12]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [13]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[::3]

array([0, 3, 6, 9])

In [16]:
arr[::2]

array([0, 2, 4, 6, 8])

In [17]:
arr[-1]

9

In [18]:
arr[-3:]

array([7, 8, 9])

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos

In [21]:
arreglo = np.array([0,1,2,3,4,5])
arreglo

array([0, 1, 2, 3, 4, 5])

In [22]:
arreglo.dtype

dtype('int32')

In [23]:
arreglo = np.array([0,1,2,3,4,5], dtype='float64')
arreglo

array([0., 1., 2., 3., 4., 5.])

In [24]:
arreglo.dtype

dtype('float64')

In [25]:
arreglo1 = np.array([0,1,2,3,4,5])
arreglo1

array([0, 1, 2, 3, 4, 5])

In [26]:
arreglo1 = arreglo1.astype(np.float64)
arreglo1

array([0., 1., 2., 3., 4., 5.])

In [27]:
arreglo1.dtype

dtype('float64')

In [28]:
arreglo2 = np.array([0,1,2,3])
arreglo2 = arreglo2.astype(np.bool_)
arreglo2

array([False,  True,  True,  True])

In [29]:
arreglo3 = np.array([0,1,2,3])
arreglo3 = arreglo3.astype(np.string_)
arreglo3

array([b'0', b'1', b'2', b'3'], dtype='|S11')

In [30]:
arreglo4 = np.array(['0','1','2','3'])
arreglo4 = arreglo4.astype(np.int8)
arreglo4

array([0, 1, 2, 3], dtype=int8)

## Dimensiones

In [31]:
escalar = np.array(45)
print(escalar)
print('Dimensión: ',escalar.ndim)

45
Dimensión:  0


In [32]:
vector = np.array([1,2,3])
print(vector)
print('Dimensión: ',vector.ndim)

[1 2 3]
Dimensión:  1


In [33]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print('Dimensión: ',matriz.ndim)

[[1 2 3]
 [4 5 6]]
Dimensión:  2


In [34]:
matriz = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(matriz)
print('Dimensión: ',matriz.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensión:  2


In [35]:
tensor = np.array([[[1,2,3],[4,5,6], [7,8,9]], [[1,2,3],[4,5,6], [7,8,9]]])
print(tensor)
print('Dimensión: ',tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensión:  3


In [36]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
print('Dimensión: ',vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensión:  10


In [37]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
print('Dimensión: ', expand.ndim)

[[1 2 3]]
Dimensión:  2


In [38]:
print(vector,'Dimensión: ',vector.ndim)
vector1 = np.squeeze(vector)
print(vector1, 'Dimensión: ',vector1.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] Dimensión:  10
[1 2 3] Dimensión:  1


## Creando arrays

In [39]:
range(0,10)

range(0, 10)

In [40]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
# (inicio, fin, cantidad_de_datos)
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [47]:
# Matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# Número aleatorio
np.random.rand()

0.6619817222896868

In [49]:
np.random.rand(4)

array([0.17425449, 0.85924387, 0.92795161, 0.24163955])

In [50]:
np.random.rand(3,3,3)

array([[[0.56408628, 0.92366837, 0.48224731],
        [0.16309724, 0.77646723, 0.72372647],
        [0.01696871, 0.19236284, 0.08967252]],

       [[0.3653915 , 0.38819408, 0.19321215],
        [0.03053656, 0.56849877, 0.06906378],
        [0.98145307, 0.22294926, 0.98919933]],

       [[0.52823996, 0.38148153, 0.9602406 ],
        [0.23483311, 0.39515943, 0.73479633],
        [0.18343191, 0.01523885, 0.29165967]]])

In [51]:
np.random.randint(1,15)

5

In [52]:
np.random.randint(1,100,(10,10))

array([[27, 76, 61, 92,  7, 49, 96, 61, 78, 19],
       [ 1,  1, 49, 50, 76, 64, 68, 59, 86, 10],
       [ 6, 13, 51, 26, 61, 47, 71, 23, 15, 67],
       [25,  3, 77, 96, 16, 63, 65, 27, 63, 43],
       [45, 66, 90,  5, 40, 15, 49, 55, 14, 64],
       [31, 14, 83,  8, 16,  4, 94, 64, 27, 92],
       [82, 52, 97, 73,  3, 15,  7, 96, 17,  6],
       [92, 47, 58, 96, 33, 70, 61, 42, 45, 19],
       [70, 59, 81, 21, 78, 16,  9, 96, 38, 97],
       [25, 16, 90, 54, 66, 89, 42, 91, 89, 28]])

In [53]:
np.random.randint(1,100,(10,10,3))

array([[[64, 11,  7],
        [24, 44, 73],
        [12, 34, 96],
        [16, 53, 40],
        [46, 40, 76],
        [38, 36, 57],
        [15,  2, 74],
        [40, 47, 24],
        [34, 68, 50],
        [24, 20, 63]],

       [[15,  6, 20],
        [61, 70,  3],
        [67,  8, 98],
        [45, 65, 83],
        [98, 22, 40],
        [31, 15, 24],
        [14, 99, 24],
        [53, 86, 65],
        [99, 40, 47],
        [73, 73, 27]],

       [[99, 42, 60],
        [75, 99, 58],
        [95, 15, 34],
        [80, 42,  1],
        [81, 77, 85],
        [57, 34, 69],
        [63, 14, 50],
        [48, 47, 97],
        [14, 10, 61],
        [82, 43, 46]],

       [[78, 66, 87],
        [64, 72, 77],
        [58, 94, 52],
        [90, 95, 14],
        [99, 87, 93],
        [14, 57, 73],
        [93, 54, 18],
        [28, 51, 46],
        [83, 19, 61],
        [34, 34, 23]],

       [[70, 45, 17],
        [37, 52, 55],
        [93, 27, 76],
        [29, 48, 56],
        [15, 37, 73],
  

## Shape y Reshape

In [54]:
arreglo = np.random.randint(1,10,(3,2))
arreglo

array([[8, 7],
       [1, 7],
       [9, 5]])

In [55]:
arreglo.shape

(3, 2)

In [56]:
arreglo.reshape(1,6)

array([[8, 7, 1, 7, 9, 5]])

In [57]:
# Si no cumple la cantidad elementos del arreglo con la nueva dimensionalidad, genera un error
#arreglo.reshape(1,7)
#ValueError: cannot reshape array of size 6 into shape (1,7)

In [58]:
arreglo.reshape(2,3)

array([[8, 7, 1],
       [7, 9, 5]])

In [59]:
np.reshape(arreglo,(1,6))

array([[8, 7, 1, 7, 9, 5]])

In [60]:
# Reorganiza por filas
np.reshape(arreglo,(2,3), 'C')

array([[8, 7, 1],
       [7, 9, 5]])

In [61]:
# Reorganiza por columnas
np.reshape(arreglo,(2,3), 'F')

array([[8, 9, 7],
       [1, 7, 5]])

In [62]:
# Reorganiza según este optimizado nuestra maquina
np.reshape(arreglo,(2,3), 'A')

array([[8, 7, 1],
       [7, 9, 5]])

## Funciones principales de NumPy

In [63]:
arreglo = np.random.randint(1,20,10)
arreglo

array([ 6, 16,  4,  3,  7, 10, 10, 16, 12, 15])

In [64]:
matriz = arreglo.reshape(2,5)
matriz

array([[ 6, 16,  4,  3,  7],
       [10, 10, 16, 12, 15]])

In [65]:
arreglo.max()

16

In [66]:
arreglo.min()

3

In [67]:
matriz.max()

16

In [68]:
matriz.min()

3

In [69]:
matriz.max(1)

array([16, 16])

In [70]:
matriz.max(0)

array([10, 16, 16, 12, 15])

In [71]:
matriz.min(0)

array([ 6, 10,  4,  3,  7])

In [72]:
# Indice donde se encuentra el valor màs grande
arreglo.argmax()

1

In [73]:
arreglo.argmin()

3

In [74]:
matriz.argmax()

1

In [75]:
matriz.argmin()

3

In [76]:
matriz.argmax(0)

array([1, 0, 1, 1, 1], dtype=int64)

In [77]:
matriz.argmin(0)

array([0, 1, 0, 0, 0], dtype=int64)

In [78]:
matriz.argmax(1)

array([1, 2], dtype=int64)

In [79]:
matriz.argmin(1)

array([3, 0], dtype=int64)

In [80]:
arreglo.ptp()

13

In [81]:
matriz.ptp()

13

In [82]:
matriz.ptp(0)

array([ 4,  6, 12,  9,  8])

In [83]:
matriz.ptp(1)

array([13,  6])

In [84]:
np.percentile(arreglo,50)

10.0

In [85]:
np.percentile(arreglo,0)

3.0

In [86]:
np.percentile(arreglo,100)

16.0

In [87]:
arreglo.sort()
arreglo

array([ 3,  4,  6,  7, 10, 10, 12, 15, 16, 16])

In [88]:
np.median(arreglo)

10.0

In [89]:
np.median(matriz,0)

array([ 6.5,  8. , 10.5, 11.5, 13. ])

In [90]:
np.median(matriz,1)

array([ 6., 15.])

In [91]:
np.std(arreglo)

4.592385001282013

In [92]:
np.var(arreglo)

21.089999999999996

In [93]:
np.mean(arreglo)

9.9

In [94]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [95]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [96]:
a

array([[1, 2],
       [3, 4]])

In [97]:
a.T

array([[1, 3],
       [2, 4]])

In [98]:
b

array([[5, 6],
       [7, 8]])

In [99]:
b.T

array([[5, 7],
       [6, 8]])

## Copy

In [100]:
arreglo = np.arange(0,11)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr = arreglo[0:6]
arr

array([0, 1, 2, 3, 4, 5])

In [102]:
arr[:] = 0
arr

array([0, 0, 0, 0, 0, 0])

In [103]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [104]:
arreglo_copy = arreglo.copy()
arreglo_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [105]:
arreglo_copy[:] = 100
arreglo_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [106]:
arreglo

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [107]:
arreglo == arreglo_copy

array([False, False, False, False, False, False, False, False, False,
       False, False])

## Condiciones

In [108]:
arreglo = np.linspace(1,10,10, dtype='int8')
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [109]:
arreglo > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [110]:
indices_condicion = arreglo > 5
indices_condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [111]:
arreglo[indices_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [112]:
arreglo[(arreglo > 5) & (arreglo < 9)]

array([6, 7, 8], dtype=int8)

In [113]:
arreglo[arreglo>5] = 99
arreglo

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [114]:
arreglo[arreglo==99]

array([99, 99, 99, 99, 99], dtype=int8)

## Operaciones

In [115]:
lista = [1,2]
lista

[1, 2]

In [116]:
lista * 2

[1, 2, 1, 2]

In [117]:
lista * 3

[1, 2, 1, 2, 1, 2]

In [118]:
arreglo = np.arange(0,10)
arreglo1 = arreglo.copy()
arreglo1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
arreglo * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [120]:
arreglo + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
1 / arreglo

C:\Users\usuario\AppData\Local\Temp\ipykernel_11916\3939086782.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arreglo


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [122]:
arreglo ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [123]:
arreglo + arreglo1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [124]:
arreglo * arreglo1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [125]:
arreglo / arreglo1

C:\Users\usuario\AppData\Local\Temp\ipykernel_11916\3264456223.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo / arreglo1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [126]:
matriz = arreglo.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
matriz1 = matriz.copy()
matriz1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [128]:
matriz + matriz1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [129]:
matriz * matriz1

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [130]:
matriz - matriz1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [131]:
# Producto punto
np.matmul(matriz, matriz1.T)

array([[ 30,  80],
       [ 80, 255]])

In [132]:
matriz @ matriz1.T

array([[ 30,  80],
       [ 80, 255]])