In [1]:
import numpy as np
import pandas as pd

In [2]:
df_books = pd.read_csv('../data/bestsellers-with-categories.csv')
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [3]:
df_books.loc[0:10, ['Name','Author']]

Name  \
0                       10-Day Green Smoothie Cleanse   
1                                   11/22/63: A Novel   
2             12 Rules for Life: An Antidote to Chaos   
3                              1984 (Signet Classics)   
4   5,000 Awesome Facts (About Everything!) (Natio...   
5       A Dance with Dragons (A Song of Ice and Fire)   
6   A Game of Thrones / A Clash of Kings / A Storm...   
7                      A Gentleman in Moscow: A Novel   
8       A Higher Loyalty: Truth, Lies, and Leadership   
9                           A Man Called Ove: A Novel   
10                          A Man Called Ove: A Novel   

                      Author  
0                   JJ Smith  
1               Stephen King  
2         Jordan B. Peterson  
3              George Orwell  
4   National Geographic Kids  
5        George R. R. Martin  
6        George R. R. Martin  
7                Amor Towles  
8                James Comey  
9            Fredrik Backman  
10           Fredrik Backman

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
arr = np.array([13,6,3,5,10])
arr

array([13,  6,  3,  5, 10])

In [6]:
arr[arr>7]

array([13, 10])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.max(arr)

13

In [9]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96